#!/bin/sh

# If there is a zero-length spark tarball, find the verison in the
# name and download from github
if ! [ -s "$1" ]; then
    scala=$(basename $1)
    version=$(echo $scala | cut -d '-' -f2 | sed 's/.tgz//')
    wget https://downloads.lightbend.com/scala/$version/$scala -O $1
fi